### ISSUE TITLE
Please "git tag" your RAKU modules versions

### ISSUE THREAD

**Issue by AntonOks** [coke/raku-zef-deps#10]
can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file?

this is highly appreciated in regards to "reproducible builds" and especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by coke** [comment]
This will happen "for free" going forward with mi6. I've seen this ticket on other repos as well, you might want to mention to people that if they use mi6, this happens automatically.

I didn't realize this module was included in Rakudo Star - might be good to let folks know when they'd added. (which maybe this is that notice)

I'll cut a release later today which should address this issue.

**Comment by AntonOks** [comment]
Thanks for the hint, I didn't know.

 

Also I don't have much of the Star modules history. Just try to keep things going and harmonize / standardize them a bit ;)


 

Thanks again!

 

Gesendet: Mittwoch, 26. April 2023 um 19:11 Uhr
Von: "Will Coleda" ***@***.***>
An: "coke/raku-zef-deps" ***@***.***>
Cc: "Anton Oks" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [coke/raku-zef-deps] Please "git tag" your RAKU modules versions (Issue #10)


 

This will happen "for free" going forward with mi6. I've seen this ticket on other repos as well, you might want to mention to people that if they use mi6, this happens automatically.

I didn't realize this module was included in Rakudo Star - might be good to let folks know when they'd added. (which maybe this is that notice)

I'll cut a release later today which should address this issue.

**Comment by coke** [comment]
Done, 0.9.7 released. ( I had gotten things setup for mi6 but hadn't pressed the button yet.)
