### ISSUE TITLE
Testing broke with zef 0.19

### ISSUE THREAD

**Issue by 2colours** [coke/raku-zef-deps#12]
Hello,

The installation will fail on the testing (basic.t) starting with zef 0.19 because of this commit: https://github.com/ugexe/zef/commit/0361a863792c6af7351c9a64bdb0384b427c82f8

It's not a difficult fix of course but maybe it would be good to think of some strategy. Ideally, there would be some CI that can retrieve new versions of zef and try to install them... I don't know. The non-API's these tests are using can break at any moment. Maybe it's actually better to _not_ test for these sort of things.

**Comment by coke** [comment]
Fixed in v0.9.8 - thanks for the report!
