### ISSUE TITLE
Some big trees might eat up memory

### ISSUE THREAD

**Issue by melezhik** [coke/raku-zef-deps#6]
Please take a look at this - https://ci.sparrowhub.io/report/1197 ( deps report ). Sparky has a relatively big dependencies tree and I guess zef-deps eats a lot of memory when try to build a tree, or maybe this a zef issue? 

HTH

Aleksei

**Comment by coke** [comment]
https://github.com/ugexe/zef/issues/467

**Comment by coke** [comment]
running zef-deps on that module got up to at least 7G used.

**Comment by coke** [comment]
possible fix is to switch back to running zef script instead of using the modules

**Comment by coke** [comment]
`zef` has addressed the issue, it'll be fixed in zef 0.14.2 - as soon as that's released, I'll update our META6.json deps and release.

**Comment by coke** [comment]
Fixed in 0.94 thanks to @ugexe, along with a **huge** speed boost.

**Comment by melezhik** [comment]
confirming - the issue has gone - https://ci.sparrowhub.io/report/1206
